export const parserPaths = {
  javascript: 'tree-sitter-javascript.wasm',
  typescript: 'tree-sitter-typescript.wasm',
  tsx: 'tree-sitter-tsx.wasm',
  // not so well supported lang...
  bash: 'tree-sitter-bash.wasm',
  c: 'tree-sitter-c.wasm',
  csharp: 'tree-sitter-c_sharp.wasm',
  css: 'tree-sitter-css.wasm',
  cpp: 'tree-sitter-cpp.wasm',
  elixir: 'tree-sitter-elixir.wasm',
  go: 'tree-sitter-go.wasm',
  html: 'tree-sitter-html.wasm',
  java: 'tree-sitter-java.wasm',
  json: 'tree-sitter-json.wasm',
  kotlin: 'tree-sitter-kotlin.wasm',
  php: 'tree-sitter-php_only.wasm',
  python: 'tree-sitter-python.wasm',
  ruby: 'tree-sitter-ruby.wasm',
  rust: 'tree-sitter-rust.wasm',
  scala: 'tree-sitter-scala.wasm',
  swift: 'tree-sitter-swift.wasm',
  yaml: 'tree-sitter-yaml.wasm',
}

export const repos = {
  bash: 'https://unpkg.com/tree-sitter-bash',
  c: 'https://unpkg.com/tree-sitter-c',
  cpp: 'https://unpkg.com/tree-sitter-cpp',
  csharp: 'https://unpkg.com/tree-sitter-c-sharp',
  css: 'https://unpkg.com/tree-sitter-css',
  go: 'https://unpkg.com/tree-sitter-go',
  html: 'https://unpkg.com/tree-sitter-html',
  java: 'https://unpkg.com/tree-sitter-java',
  javascript: 'https://unpkg.com/tree-sitter-javascript',
  json: 'https://unpkg.com/tree-sitter-json',
  php: 'https://unpkg.com/tree-sitter-php',
  python: 'https://unpkg.com/tree-sitter-python',
  ruby: 'https://unpkg.com/tree-sitter-ruby',
  rust: 'https://unpkg.com/tree-sitter-rust',
  scala: 'https://unpkg.com/tree-sitter-scala',
  tsx: 'https://unpkg.com/tree-sitter-typescript',
  typescript: 'https://unpkg.com/tree-sitter-typescript',
}

// https://github.com/ast-grep/ast-grep/blob/main/crates/language/Cargo.toml
export const versions: Record<string, string> = {
  bash:  "0.23.3",
  c:  "0.23.5",
  cpp:  "0.23.4",
  csharp:  "0.23.1",
  css:  "0.23.1",
  go:  "0.23.4",
  html:  "0.23.2",
  java:  "0.23.5",
  javascript:  "0.23.1",
  json:  "0.24.2",
  php:  "0.23.11",
  python:  "0.23.3",
  ruby:  "0.23.1",
  rust:  "0.23.2",
  scala:  "0.23.4",
  tsx: "0.23.2",
  typescript: "0.23.2",
}